### PR TITLE
Add example for ruby

### PR DESCRIPTION
**Pull request by luong-komorebi**
Because there is no example in the openzipkin org. 
https://github.com/openzipkin?utf8=%E2%9C%93&q=example&type=&language=ruby will return no result

### CODE REVIEW

**Comment by adriancole** [comment]
are you up to making a port of our standard example? if so, I could open a repo for you. In that repo, you could make a branch that also uses sidekiq.

**Comment by luongvo209** [comment]
@adriancole yeah I am pleased to do that. But before you open that repo, I suggest that I would open a repo on my side (that would be luongvo209/zipkin-ruby-example). I would post a reply here and tag you into that repo when everything is finished and ready to be reviewed. Then after everything looks good to go, we would migrate it to the openzipkin org. How does that sound to you?

**Comment by adriancole** [comment]
sounds good to me

**Comment by luongvo209** [comment]
@jcarres-mdsol Yes definitely. 
Also, if you have plans to write an example, go ahead. Follow your plan. Don't mind me 👍

**Comment by jcarres-mdsol** [comment]
No plan, waiting for your example 👯‍♂️

**Comment by adriancole** [comment]
I created the canonical example here. feel free to help make things more idiomatic, though the routes as they are defined is important (as it lets other people help troubleshoot tracer issues even if they don't know ruby) https://github.com/openzipkin/zipkin-ruby-example

**Comment by luong-komorebi** [comment]
Sorry for letting this hang for too long. I was too busy with OpenCensus. I think we should work more on your example and allow me to close this so efforts are focused in one place only.

**Comment by adriancole** [comment]
thanks for the spike, Luong and no worries.. I needed the example to verify
a bug so scrapped it together. Your code here helped.

PS one approach that works really well is to create a branch for extra
integrations. This provides a "diff" approach without needing to clutter
the main example which should both be canonical and simple as possible.
Here's an example.. you could imagine adding a diff that adds sidekiq
https://github.com/openzipkin/sleuth-webmvc-example

**Pull request closed without merging**
